In [9]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

## Cleaning UNData (might convert to .py later as a function)

In [22]:
# write the function UNDataCleaning.py
def UNDataCleaning(country:str, csv_name:str, indicator_num: str): #all country name has capital for first letter
    df = pd.read_csv(f'../data/{country}/UNData/{csv_name}')
    df = df[['SeriesDescription', 'TimePeriod', 'Value']]
    df.dropna(inplace=True)
    df_pivot = df.pivot(index = ['TimePeriod'],
                    columns = 'SeriesDescription',
                    values = 'Value').reset_index()
    df_pivot.columns.name = None
    df_pivot.rename(columns = {'TimePeriod': 'Year'}, inplace = True)
    df_pivot.to_csv(f'../data/{country}/UNData/{indicator_num}Tidy.csv', index = False)

In [24]:
# example Usage 
UNDataCleaning(country= 'Thailand', csv_name='series-ER_CBD_SMTA-764.csv', indicator_num= '15.6.1')

### Archived (used for testing)

In [18]:
df = pd.read_csv('../data/Thailand/UNData/series-AG_LND_FRSTCERT-764.csv')
df

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,TimePeriod,Value,Time_Detail,...,UpperBound,LowerBound,BasePeriod,Source,GeoInfoUrl,FootNote,[Nature],[Observation Status],[Reporting Type],[Units]
0,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2000.0,0.00,2000.0,...,NaN,NaN,NaN,No data on certified forest area in the FSC an...,NaN,No certified forest area,C,A,G,HA_TH
1,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2005.0,2.94,2005.0,...,NaN,NaN,NaN,Data submitted by FSC and PEFC secretariats (c...,NaN,NaN,C,A,G,HA_TH
2,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2010.0,7.64,2010.0,...,NaN,NaN,NaN,Data submitted by FSC and PEFC secretariats (c...,NaN,NaN,C,A,G,HA_TH
3,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2015.0,44.24,2015.0,...,NaN,NaN,NaN,Data submitted by FSC and PEFC secretariats (c...,NaN,NaN,C,A,G,HA_TH
4,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2016.0,61.80,2016.0,...,NaN,NaN,NaN,Data submitted by FSC and PEFC secretariats (c...,NaN,NaN,C,A,G,HA_TH
5,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2017.0,63.37,2017.0,...,NaN,NaN,NaN,Data submitted by FSC and PEFC secretariats (c...,NaN,NaN,C,A,G,HA_TH
6,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2018.0,56.88,2018.0,...,NaN,NaN,NaN,Data submitted by FSC and PEFC secretariats (c...,NaN,NaN,C,A,G,HA_TH
7,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2019.0,75.78,2019.0,...,NaN,NaN,NaN,Data submitted by FSC and PEFC secretariats (c...,NaN,NaN,C,A,G,HA_TH
8,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2020.0,88.67,2020.0,...,NaN,NaN,NaN,Data submitted by FSC and PEFC secretariats (c...,NaN,NaN,C,A,G,HA_TH
9,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2021.0,118.05,2021.0,...,NaN,NaN,NaN,Data submitted by FSC and PEFC secretariats (c...,NaN,NaN,C,A,G,HA_TH
10,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2022.0,125.64,2022.0,...,NaN,NaN,NaN,Data submitted by FSC and PEFC secretariats (c...,NaN,NaN,C,A,G,HA_TH
11,15.0,15.2,15.2.1,AG_LND_FRSTCERT,Forest area certified under an independently v...,764.0,Thailand,2023.0,150.22,2023.0,...,NaN,NaN,NaN,FSC and PEFC (forest certification organizations),NaN,NaN,C,A,G,HA_TH
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df[['SeriesDescription', 'TimePeriod', 'Value']]
df

                                    SeriesDescription  TimePeriod   Value
0   Forest area certified under an independently v...      2000.0    0.00
1   Forest area certified under an independently v...      2005.0    2.94
2   Forest area certified under an independently v...      2010.0    7.64
3   Forest area certified under an independently v...      2015.0   44.24
4   Forest area certified under an independently v...      2016.0   61.80
5   Forest area certified under an independently v...      2017.0   63.37
6   Forest area certified under an independently v...      2018.0   56.88
7   Forest area certified under an independently v...      2019.0   75.78
8   Forest area certified under an independently v...      2020.0   88.67
9   Forest area certified under an independently v...      2021.0  118.05
10  Forest area certified under an independently v...      2022.0  125.64
11  Forest area certified under an independently v...      2023.0  150.22
12                                                NaN         NaN     NaN

In [12]:
# drop the NaN value and rename TimePeriod to Year
df.dropna(inplace=True)

/var/folders/5n/m32d0hsx4959r42x3mssyjj40000gn/T/ipykernel_30594/334067596.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [13]:
# Use Pivot to change series description to a column
df_pivot = df.pivot(index = ['TimePeriod'],
                    columns = 'SeriesDescription',
                    values = 'Value').reset_index()
df_pivot.columns.name = None
df_pivot

,TimePeriod,Forest area certified under an independently verified certification scheme (thousands of hectares)
0,2000.0,0.00
1,2005.0,2.94
2,2010.0,7.64
3,2015.0,44.24
4,2016.0,61.80
5,2017.0,63.37
6,2018.0,56.88
7,2019.0,75.78
8,2020.0,88.67
9,2021.0,118.05
10,2022.0,125.64
11,2023.0,150.22

In [17]:
df_pivot.rename(columns = {'TimePeriod': 'Year'}, inplace = True)
df_pivot

,Year,Forest area certified under an independently verified certification scheme (thousands of hectares)
0,2000.0,0.00
1,2005.0,2.94
2,2010.0,7.64
3,2015.0,44.24
4,2016.0,61.80
5,2017.0,63.37
6,2018.0,56.88
7,2019.0,75.78
8,2020.0,88.67
9,2021.0,118.05
10,2022.0,125.64
11,2023.0,150.22

In [21]:
df_pivot.to_csv(f'../data/Thailand/UNData/15.2.1Tidy.csv', index = False)